### ISSUE TITLE
Minor suggestion : add an optional default_bg/default_fg in console_new

### ISSUE THREAD

**Issue by FractalWire** [libtcod/libtcod#10]
Hey ! it's me again,

So, I've been experimenting with the deault_bg/default_fg attribute of the console object and was a bit confused why it was not working properly.
It was actually working properly, but I just wasn't using it right.
I was doing : 
```
con = tcod.console_new(w,h)
con.default_bg = (20,20,20)
```
While I really should have done this : 
```
con = tcod.console_new(w,h)
con.default_bg = (20,20,20)
con.clear()
```
Which I find a bit weird but it makes sense.
However, I think we could make it a little less weird by initializing the default_bg/fg when creating a new console.
Something like that would be nice : 
```
con = tcod.console_new(w,h,default_bg = (20,20,20))
```

What do you think ?

**Comment by HexDecimal** [comment]
This proposal is pretty solid.  Unfortunately my future plans involve removing the default attributes entirely from libtcod.

Also `con.clear()` is not implied when creating a new console.  Consoles start with a default_fg of white but the foreground is still black after a console is created.  Fixing this would cause a minor incompatibility, but it'd be better than the current behavior.

I'll go ahead and implement this.

**Comment by FractalWire** [comment]
> This proposal is pretty solid. Unfortunately my future plans involve removing the default attributes entirely from libtcod.

Well, I don't know about default_bg_blend or default_alignement (I don't experiment with those yet) but default_bg/fg saves me the hassle to do that : 
```
con.clear()
con.bg[:] = my_bg_color
con.fg[:] = my_fg_color
```
every time I use `clear()`
And I guess it might be a bit more efficient to not have to do that every time.

**Comment by HexDecimal** [comment]
I've added code that resolves the main issue.  I can release it immediately if you want to mess with it.

A problem is that when these kinds of parameters are implicit they can be forgotten and cause weird bugs to show up when someone inevitably forgets to set them.  I know this from experience.

For `clear` a simple solution might be to have it take `fg` and `bg` colors as parameters.   I'll go ahead and implement this:
```python
con = tcod.console.Console(w, h)
con.clear(bg=(20, 20, 20))
```

**Comment by FractalWire** [comment]
Do you consider optional parameters as implicit ?
I have to say, I don't have enough experience with python to say if implicit parameters are bad, so I trust you on that.

However, if you keep a default_bg/fg option that can be set on console creation, clear do not need some optional parameters in my opinion.
clear should really do only what it's meant to do : put back the console back to its default state.
With those parameters, clear became a drawing method too.

(You can release whenever you feel ready ;)

**Comment by HexDecimal** [comment]
I've deprecated the default values, which is pretty much the opposite of what you asked for so I apologize for that.

The issues with the default values became more clear when I updated the samples to remove them and I just had no idea what the values were for any of the print and clear functions.  I ended up writing special deprecation warnings that explain what the values are when those functions are called.

If you have any examples of what you planned on using the defaults for then I can try and provide you with an elegant alternative solution.

**Comment by FractalWire** [comment]
Hey !

I'm not sure to understand your issue for not knowing the default value. You could always get them with console.default_bg

However, I do understand your concern regarding the interaction between print_ and default_value.
As print_ did not have any way to specify the color to print with, you were forced to use stuff like : 
```
console.default_bg = new_color
console.print_(x,y,value)
console.default_bg = old_color
```
To print with the wanted color, which I agree, is ugly.
I was not really aware of this behaviour before.

Your new print implementation is an improvement in that regard, however, it could still work well with default value and still print value with whatever color you'd like, painlessly. I'll raise a new issue to explain my point better.

Here is a quick example of what I'd like to have : 
```
console = Console(width,height,default_bg = color1)

print(x,y,value) # print value at position x,y with bg_color=color1

console.bg[:] = color2
print(x,y,value2) # print value2 at x,y with bg_color=color2

print(x,y,value3,bg_color=color3) # print value3 at x,y with bg_color=color3

console.default_bg = color4
console.clear()
print(x,y,value4) # print value4 at position x,y with bg_color=color4

console.bg[y,x] = color5
print(x,y,value5) # print value5 at position x,y with bg_color=color4 except for first character where bg_color=color5
```
