### ISSUE TITLE
Cannot running examples due to "ERROR: Permission denied for user: 'None'. [Remote: hexdecimal]"

### ISSUE THREAD

**Issue by lychees** [libtcod/libtcod#108]
I am trying to run the examples through [the documents](https://github.com/libtcod/libtcod/tree/develop/samples).
```conan install . -if build```

```
ERROR: Permission denied for user: 'None'. [Remote: hexdecimal]
```

**Comment by HexDecimal** [comment]
I haven't touched Conan in a long time, so the Conan builds must be very out-of-date if they still exist at all.

Right now if you want to build the samples you follow the [CONTRIBUTING.md](https://github.com/libtcod/libtcod/blob/develop/CONTRIBUTING.md) instructions and use VSCode/CMake/Vcpkg.

**Comment by lychees** [comment]
Cool. 
(But it mentioned "This is only recommended for libtcod developers" 😂.)

**Comment by HexDecimal** [comment]
Sorry for that.  I'll need to remove the old Conan instructions sometime.

The samples are mostly for development, if you were just trying to get a project started then you'd want to use the [template project](https://github.com/HexDecimal/libtcod-vcpkg-template).

**Comment by HexDecimal** [comment]
Now the readme which told you to use Conan points to CONTRIBUTING.md.  If you're still having trouble compiling them then I can explain how the build systems work.
