### ISSUE TITLE
Could not find a correct configuration file for package "libtcod" via vcpkg with “emscripten“

### ISSUE THREAD

**Issue by lychees** [libtcod/libtcod#109]
Hi, after successful building ``libtcod-vcpkg-template`` locally, I am trying to use ``libtcod`` together with ``easyrpg multiplayer client`` in order to build a multiplayer roguelike game which can be run in a browser. There is a lot of dependence include "emscripten" in the client code (they even have [a script](https://github.com/EasyRPG/buildscripts/) to handle all of them!), So I try to use the ``vcpkg`` method. After some modification with ``CMakeLists.txt``, it seems that Cmake find the libtcod library but cannot use it.

```
ubuntu@ip-172-26-1-83:~/workdir/ynoclient$ ./cmake_build.sh
CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:782 (_find_package):
  Could not find a configuration file for package "libtcod" that is
  compatible with requested version "".

  The following configuration files were considered but not accepted:

    /home/ubuntu/workdir/ynoclient/vcpkg/packages/libtcod_x64-linux/share/libtcod/libtcodConfig.cmake, version: 1.20.1 (64bit)

Call Stack (most recent call first):
  CMakeLists.txt:656 (find_package)


-- Configuring incomplete, errors occurred!
```

You can find my code and modification here: https://github.com/lychees/ynoclient/commit/5683aa24c88d7c412015b6875e2c89a027137c1f
It might not be a bug with libtcod, but it is really hard to find some help elsewhere.

I build easyrpg with cpp14 but libtcod is running with cpp17, will this have some side effects?
Regards

**Comment by HexDecimal** [comment]
Are you trying to build an 32-bit executable with the 64-bit library?  I also see `DVCPKG_TARGET_TRIPLET=wasm32-emscripten` in your files, but the config file shows `x64-linux`.

> I build easyrpg with cpp14 but libtcod is running with cpp17, will this have some side effects?

Libtcod C++ headers will not parse with C++14.

**Comment by HexDecimal** [comment]
You'll probably need to tell Vcpkg to install `libtcod:wasm32-emscripten`.  Or setup Vcpkg's manifest mode if you want the library installed automatically.

**Comment by lychees** [comment]
It works. Thanks a lot!
