### ISSUE TITLE
Console.set_key_color() not working

### ISSUE THREAD

**Issue by FractalWire** [libtcod/libtcod#11]
So, I've continued to test the Console class and the `set_key_color` method seems to not work.
The `key_color` as a blit argument works fine though.

Those lines in the blit method seems to be what's causing the issue : 
```
        if key_color or self._key_color:
            key_color = ffi.new("TCOD_color_t*", key_color)
```

**Comment by HexDecimal** [comment]
I now have a fix ready, although I kind of feel like I should also just deprecate the set_key_color functions while I'm on this since I've already added the ability to pass the key color directly to the blit method.

This has been really helpful.

**Comment by FractalWire** [comment]
Yes I agree with the deprecation
