### ISSUE TITLE
GCC 12 breaking change

### ISSUE THREAD

**Issue by sosein** [libtcod/libtcod#116]
When I compile libtcod or my application using it with GCC 12 I get the following error.

```
/usr/include/libtcod/config.h:84:30: error: standard attributes in middle of decl-specifiers
   84 | #define TCOD_DEPRECATED(msg) [[deprecated(msg)]]
      |                              ^
/usr/include/libtcod/mersenne_types.h:86:9: note: in expansion of macro ‘TCOD_DEPRECATED’
   86 | typedef TCOD_DEPRECATED("This type hides indirection.  Use TCOD_Random* instead.") union TCOD_Random* TCOD_random_t;
      |         ^~~~~~~~~~~~~~~
/usr/include/libtcod/config.h:84:30: note: standard attributes must precede the decl-specifiers to apply to the declaration, or follow them to apply to the type
   84 | #define TCOD_DEPRECATED(msg) [[deprecated(msg)]]
      |                              ^
```

I believe this is due to a breaking change introduced in [GCC 12](https://www.gnu.org/software/gcc/gcc-12/changes.html):
> Stricter checking of attributes on friend declarations: if a friend declaration has an attribute, that declaration must be a definition. Moreover, a C++11 attribute cannot appear in the middle of the decl-specifier-seq. ([PR99032](https://gcc.gnu.org/PR99032))

**Comment by sosein** [comment]
Seems like the fix is just changing

https://github.com/libtcod/libtcod/blob/e792ae83e39182bf1293659723610761da5cf03f/src/libtcod/mersenne_types.h#L86

to

```cpp
TCOD_DEPRECATED("This type hides indirection.  Use TCOD_Random* instead.") typedef union TCOD_Random* TCOD_random_t;
```

**Comment by HexDecimal** [comment]
Thanks for pointing this out.  I didn't know that attributes could apply when put before the typedef keyword until I looked it up just now.

I'll have a quick fix, but it seems the only way to prevent this in the future would be to use GCC 12 in the CI.
