### ISSUE TITLE
Historical issue

### ISSUE THREAD

**Issue by nataraj-hates-MS-for-stealing-github** [libtcod/libtcod#119]
Please consider setting 1.5.2 tag to 8e07ea00d0a8952cac9da6e9b6e701e8d88ce5a0 commit... 

For those who updates code that is outdate long time ago, it might be useful

**Comment by HexDecimal** [comment]
[It is done](https://github.com/libtcod/libtcod/releases/tag/1.5.2).  While I can add tags for any of these older releases I can't easily make cross-platform builds of them, but that kind of thing is possible if there's time to do it.

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
Thank!

> I can't easily make cross-platform builds of them

There is no need in that. Experienced digital archeologist can do it himself, if he needs it. But not skipping one of the tags may be important in some rare cases.

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
BTW, out of curiosity. The svn repo from which current git repo was imparted, is is completely lost, or somebody has a local copy of it?

**Comment by HexDecimal** [comment]
The SVN repo was gone before I became a contributor.  I don't have a backup of it.

**Comment by HexDecimal** [comment]
The Git repo was imported from Bitbucket's Mercurial repo, but the import to Bitbucket from SVN seemed to squash the commits.  Bitbucket did not handle preservation very well.

Jice might have a copy or know who had access to the SVN repo.  Right now I'm the only one maintaining libtcod and this repo is all that officially exists. Bitbucket thought it was a good idea to purge all their Mercurial repos.

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
Can you ask Jice?

I have experience of cherry-picking commits from svn into git repo in similar case... If you find this interesting and it we find svn repo I can give it a try... I am it-archeologist ;-)

**Comment by HexDecimal** [comment]
@jice-nospam Any chance you have the SVN repository of libtcod from before it was imported to Bitbucket or know anyone else who might have a copy of it?

**Comment by jice-nospam** [comment]
Hey, I don't have the SVN repo but I might be able to recover old releases including source code that you could reinject in the git history,  I'll check that tonight and come back to you

**Comment by jice-nospam** [comment]
So I have the 1.5.0 source code and also a copy of the svn repository from 2011 but it's an old version of svn and so far all my attempts to restore it to a recent svn have failed. Here are both the files in case you can get something out of them. I'll come back to you if I manage to import the svn in a git repository.
[libtcod-svn-repo.zip](https://github.com/libtcod/libtcod/files/9203758/libtcod-svn-repo.zip)
[libtcod-1.5.0.zip](https://github.com/libtcod/libtcod/files/9203768/libtcod-1.5.0.zip)

**Comment by HexDecimal** [comment]
Thanks!  I've successfully imported that SVN repo into Git (or at least started it, it's taking a while.)  I'll try to upload this, but I don't plan on overwriting the history right now.

**Comment by jice-nospam** [comment]
Great!

**Comment by HexDecimal** [comment]
It's more, SVN, than I expected.  It's clear that it needs some kind of cleaning up.  For now I've uploaded to the `svn` branch on this repo:
https://github.com/libtcod/libtcod/tree/svn

**Comment by HexDecimal** [comment]
@jice-nospam Do you know the emails for `dividee` and `joeosborn` so I can correctly attribute them?  Git can't extract the emails from SVN, I'm not setup to run SVN commands on this, and I can't find anything from the usernames alone.

**Comment by jice-nospam** [comment]
Here is Joe osborn : https://github.com/JoeOsborn

Le mer. 27 juil. 2022 à 11:36, Kyle Benesch ***@***.***> a
écrit :

**Comment by jice-nospam** [comment]
And here are more files for historians @nataraj-hates-MS-for-stealing-github :)
[libtcod-1.4.3-MSVC.zip](https://github.com/libtcod/libtcod/files/9206509/libtcod-1.4.3-MSVC.zip)
[libtcod-1.3.2-linux.tar.gz](https://github.com/libtcod/libtcod/files/9206510/libtcod-1.3.2-linux.tar.gz)
[libtcod-1.3.2-mingw32.zip](https://github.com/libtcod/libtcod/files/9206511/libtcod-1.3.2-mingw32.zip)
[libtcod-1.3.2-VS.zip](https://github.com/libtcod/libtcod/files/9206512/libtcod-1.3.2-VS.zip)
[libtcod-1.4.0-linux.tar.gz](https://github.com/libtcod/libtcod/files/9206513/libtcod-1.4.0-linux.tar.gz)
[libtcod-1.4.0-mingw32.zip](https://github.com/libtcod/libtcod/files/9206515/libtcod-1.4.0-mingw32.zip)
[libtcod-1.4.0-VS.zip](https://github.com/libtcod/libtcod/files/9206516/libtcod-1.4.0-VS.zip)
[libtcod-1.4.1-linux.tar.gz](https://github.com/libtcod/libtcod/files/9206517/libtcod-1.4.1-linux.tar.gz)
[libtcod-1.4.1-linux64.tar.gz](https://github.com/libtcod/libtcod/files/9206519/libtcod-1.4.1-linux64.tar.gz)
[libtcod-1.4.1-mingw32.zip](https://github.com/libtcod/libtcod/files/9206521/libtcod-1.4.1-mingw32.zip)
[libtcod-1.4.1-MSVC.zip](https://github.com/libtcod/libtcod/files/9206522/libtcod-1.4.1-MSVC.zip)
[libtcod-1.4.1-osx.zip](https://github.com/libtcod/libtcod/files/9206523/libtcod-1.4.1-osx.zip)
[libtcod-1.4.2-linux.tar.gz](https://github.com/libtcod/libtcod/files/9206525/libtcod-1.4.2-linux.tar.gz)
[libtcod-1.4.2-linux64.tar.gz](https://github.com/libtcod/libtcod/files/9206527/libtcod-1.4.2-linux64.tar.gz)
[libtcod-1.4.2-mingw32.zip](https://github.com/libtcod/libtcod/files/9206528/libtcod-1.4.2-mingw32.zip)
[libtcod-1.4.2-MSVC.zip](https://github.com/libtcod/libtcod/files/9206529/libtcod-1.4.2-MSVC.zip)

**Comment by jice-nospam** [comment]
[libtcod-1.4.3-mingw32.zip](https://github.com/libtcod/libtcod/files/9206562/libtcod-1.4.3-mingw32.zip)
[libtcod-1.4.3-linux.tar.gz](https://github.com/libtcod/libtcod/files/9206566/libtcod-1.4.3-linux.tar.gz)
[libtcod-1.4.3-linux64.tar.gz](https://github.com/libtcod/libtcod/files/9206570/libtcod-1.4.3-linux64.tar.gz)
[libtcod-1.5.0-MSVC.zip](https://github.com/libtcod/libtcod/files/9206573/libtcod-1.5.0-MSVC.zip)
[libtcod-1.5.0-haiku.zip](https://github.com/libtcod/libtcod/files/9206577/libtcod-1.5.0-haiku.zip)
[libtcod-1.5.0-linux.tar.gz](https://github.com/libtcod/libtcod/files/9206578/libtcod-1.5.0-linux.tar.gz)
[libtcod-1.5.0-linux64.tar.gz](https://github.com/libtcod/libtcod/files/9206580/libtcod-1.5.0-linux64.tar.gz)
[libtcod-1.5.0-mingw32.zip](https://github.com/libtcod/libtcod/files/9206581/libtcod-1.5.0-mingw32.zip)

**Comment by jice-nospam** [comment]
@HexDecimal dividee mail was ibatugow@gmail.com back in the time

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
Thanx @HexDecimal , @jice-nospam !
Downloaded it to my storage. Will play with it once...

**Comment by HexDecimal** [comment]
Those older binary builds will be useful.  I've seen people ask for them before, but I didn't have them.

I've considered merging the histories but files at the head of the SVN repo don't match the files at the base of the current main branch and I'm not sure how to resolve that, other than maybe adding a commit on the SVN head resetting all files to the main base commit.

The commit history implies that there's even more missing history from Google Code. I'm just glad the SVN repo was available.

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
> the head of the SVN repo don't match the files at the base of the current main branch and I'm not sure how to resolve that, other than maybe adding a commit on the SVN head resetting all files to the main base commit.

it is the only way. Hopefully this diff will not be really big

> The commit history implies that there's even more missing history from Google Code. I'm just glad the SVN repo was available.
Yeah, I've noticed that too...

I also give a short glance to the svn import you've make. I see there some switches of trunk between the branches, that look nasty.  You've imported only trunk, but not the rest of branches. Am I right?

**Comment by HexDecimal** [comment]
> it is the only way. Hopefully this diff will not be really big

It doesn't seem to be that big, but it looks like stuff is missing between the current SVN head and when it was uploaded to Bitbucket.

> I also give a short glance to the svn import you've make. I see there some switches of trunk between the branches, that look nasty. You've imported only trunk, but not the rest of branches. Am I right?

Importing everything is an option (everything being files stored in trunk/tags/branches/etc subfolders,) but I switched to importing just the trunk and tags.  The branches were usually temporary and leftover, I'd likely remove them if they were imported.

I assume the trunk jumping between branches will still happen no matter what if it's an SVN issue.  Importing the full structure then resetting the files afterwards might have an affect on preserving blame history, but I mostly wanted the older tags.

**Comment by HexDecimal** [comment]
Continuing this is going to be difficult.  I'm going to reopen this and give some info on what I've done so far.

Here's the `users.txt` authors file in case anyone else wants to import the SVN repo to Git.
```
jice = jice <jice.nospam@gmail.com>
mingos = Dominik Marczuk <mingos.nospam@gmail.com>
donblas = Chris "donblas" Hamons <chris.hamons@microsoft.com>
dividee = dividee <ibatugow@gmail.com>
jotaf = Jotaf <jotaf98@hotmail.com>
joeosborn = joeosborn <joseph.osborn@pomona.edu>
```
The repository archive can be extracted to a directory and then imported to Git by providing a URI to the folder.
```
git svn clone file:///c/Projects/libtcod-svn-repo --authors-file=users.txt --no-metadata --prefix "" -s libtcod
```
More details on importing to Git from SVN can be found here:
https://git-scm.com/book/en/v2/Git-and-Other-Systems-Migrating-to-Git

You can add the libtcod GitHub repo as a remote to fetch its branches and try to merge them if you want to try that.

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
I have my vacations till the end of the week.
First priority is to my "build gobin-camp" project.  Then I might have a look at the reops...

**Comment by jice-nospam** [comment]
I can give it a try, but reinserting the old history means rebasing the whole existing history. This will cause a lot of issue for people having clones and forks. Isn't it simpler to just keep the old versions in the svn branch so that people can still checkout the old versions tags ?

**Comment by HexDecimal** [comment]
I was thinking of that.  Just having it as a separate branch might be enough or might be better.  Another alternative would be some kind of merge that combines the histories rather than a rebase.

Right now seems pretty good actually.  I have the old history and I have the version tags for that history.  For most users it isn't going to matter that the older versions are technically in an orphaned branch.  Tampering with the history by trying to rebase it will possibly lose information rather than add it.

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
![изображение](https://user-images.githubusercontent.com/48326335/182764550-4912409f-bcec-4bd3-b86f-3d3ca94f0499.png)

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
Hi!
I did the thing... Please have a look https://gitlab.com/dhyannataraj/libtcod-svn-history/-/network/svn_1.5
There are several branches, that displays what have been happening to the project.

`svn_1.5_deprecated` have been imported from google code as a 1.5 developement branch. They developed it for a while and then claimed it to be depeicated, and created a new branch 1.5 from current 1.4 branch.

`svn_1.4` have been imported from google. They imported it right, first imported 1.4.1 stable release, and then overwriten it with development 1.4.x branch. So we have `1.4.1` and `1.4.2` releases. There also have been 1.4.3 release that have not been released, but renamed to new 1.5.0. I've tagged last commit of 1.4.3 future release as `1.4.3_RC`. 

`svn_1.5` branch is growing from `svn_1.4` branch. It has one release tag `1.5.0`, and has sub-branch `svn_1.5.0` with one backported feature. `svn_1.5` ends with version 1.5.1 not being released yet. So I marked the last commit of svn_1.5 as `1.5.1_RC` as last known commit for 1.5.1.

So we have all releases tagged, and two versions that have not been released under their original names, tagged with RC suffix.

Also I'd like to notice, there was a total mess in the svn repo with mixing LF and CRLF line feeds. For example in rev 98 "put back 1.4 on the trunk" they switch trunk to the actual content of 1.4 branch, but with different set of line feeds than 1.4 had. This make preserving keeping track of history, the way as it is, impossible. So I changed script setting to ignore CR in line feeds while building git repo. That gave us consisted history of the newly imported repo, but it make impossible rebasing current master over history branch, as current master has CRLFs in the starting commit. Rebasing is still possible, but will require more work to bring linefeed issue in sync... But as far as I got, you are not really interested in rebasing...

So, feel free to import svn-history branches from my repo.

I also attach files and scripts I used to do it:
[scripts_used.tar.gz](https://github.com/libtcod/libtcod/files/9274820/scripts_used.tar.gz)

May be later on I will write some article, describing how did I do it.

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
Oh... I missed static archives for 1.4.0 and 1.3.2. I guess I have some more work to be done, @HexDecimal do not import the repo :-)

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
@HexDecimal please have a look again: https://gitlab.com/dhyannataraj/libtcod-svn-history/-/network/svn_1.5
Now I have 1.3.2 and 1.4.0 archives imported into the repository...

**Comment by HexDecimal** [comment]
I've mirrored the tags.  I'm not so sure what to do with the branches.

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
How did you import your svn branch?

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
my branches is not the same as your svn branch... Your svn branch has commits missing and do not properly preserve history.

How did you imported the svn branch into this repo? Can you remove it and then import my branches the same way?

**Comment by HexDecimal** [comment]
I'll be forcing anything here to point at yours, but I won't need to keep anything other than the versioned tags.  Any branches not merged into a tagged branch need to be resolved, but they're too stale to work with.

**Comment by HexDecimal** [comment]
I've already updated the versioned tags, you should ignore the current `svn` branch from this repo, which I'll probably remove.

**Comment by HexDecimal** [comment]
I can technically import your non-tag branches any way I want to, but having them as branches will mess up the workflow.

**Comment by HexDecimal** [comment]
`svn_1.5_deprecated`, it looks like most of this is duplicate commits already added to the main branch, so I don't think I need to keep this.

`svn_1.5.0` looks merged so I won't need to keep it.

`svn_1.4` only adds a "this branch is finished, switch to the next one" warning which is not useful in the history.

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
I guess you can import my svn_1.5 branch instead of your svn, and name it any way you like. This should do the trick...

**Comment by HexDecimal** [comment]
The [1.5.1-rc](https://github.com/libtcod/libtcod/tree/1.5.1-rc) tag includes the last commit of the `svn_1.5` branch.  If you really want I could add another tag that says it's to the last SVN revision.

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
Do we have final version of 1.5.1 release? If we have, 1.5.1-rc can be safely removed...

**Comment by HexDecimal** [comment]
`1.5.1` exists in the main branch.  Removing `1.5.1-rc` will lose the commits leading up to it unless it's changed to a branch, another tag, or is merged.

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
I guess it will be good idea to put svn branch head there, and mark it as archive branch

**Comment by HexDecimal** [comment]
Because `1.5.1-rc` might be inaccurate?  I'll replace it with an `svn-archive` tag.

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
Can it be `svn-archive` branch? Tag is to pin certain commit. Branche is to mark chain of commits. Here we certainly have chain of commits... From 1.3.2 till svn have been abandoned...

**Comment by HexDecimal** [comment]
Maybe.  Both tags and branches can be used like that, but I want to use branches for development and tags for archival.

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
You can pinpoint branch head with a tag. This will work but this will be confusing both for git engine and git users...

If you look at https://github.com/libtcod/libtcod/tree/1.4.2, it has `This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.` message

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
So I will be humbly insisting on keeping it as a branch (as an exception may be), because I consider this really importaint

**Comment by HexDecimal** [comment]
> This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.

I've noticed that too, and it's still there even if the `svn` branch exists.  I think it shows up as long as the tag isn't connected to the main branch.

**Comment by HexDecimal** [comment]
I think the way to remove that warning would be to actually merge it with the main branch, but I'm not sure of the repercussions of doing this.

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
> I've noticed that too, and it's still there even if the svn branch exists. I think it shows up as long as the tag isn't connected to the main branch.

I am not sure about it... Can we check it?

**Comment by HexDecimal** [comment]
Looks like I was mistaken.  Since I had the SVN branch before and I remembered encountering the warning around then.

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
> Looks like I was mistaken. Since I had the SVN branch before and I remembered encountering the warning around then.

Can we keep it this way? If I have a with request after importing this old repo into git, I will use it for it... ;-)

**Comment by HexDecimal** [comment]
It's done.  `svn-archive` is now a branch and I've protected it to prevent any accidents.  All the old tags except for `1.5.1-rc` are uploaded.

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
Cool! Thank you!

**Comment by HexDecimal** [comment]
I'm going to consider this resolved.  I've also went and uploaded the older builds to the releases page.

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
Placed script I used it the repo https://gitlab.com/dhyannataraj/svn-to-git-full-import
and write some explanations about it. So it can be reused by others.
