### ISSUE TITLE
Error when configuring project with CMake -> Fatal: path 'versions/baseline.json' exists on disk, but not in <commit>

### ISSUE THREAD

**Issue by ljfp** [libtcod/libtcod#121]
I was following the instructions to build libtcod for development from here: https://github.com/libtcod/libtcod/blob/main/CONTRIBUTING.md
When I got stuck in this step:
-CMake Tools will ask permission to configure the project, select yes.

Everytime CMakte try to configure the project, it always fails in the same step:

```
-- Running vcpkg install
Error: while checking out baseline from commit '0cf5b4305ba811d069d3ce328261eeb54bf61c3a' at subpath 'versions/baseline.json':
fatal: path 'versions/baseline.json' exists on disk, but not in '0cf5b4305ba811d069d3ce328261eeb54bf61c3a'

This may be fixed by updating vcpkg to the latest master via `git pull` or fetching commits via `git fetch`.

You can use the current commit as a baseline, which is:
    "builtin-baseline": "a34997af6c00d3e5711a4a75428c34a99a5f1c8b"
```

But this line is simply not true -> "fatal: path 'versions/baseline.json' exists on disk, but not in '0cf5b4305ba811d069d3ce328261eeb54bf61c3a'"
You can see here that the path mentioned above existed on that commit: https://github.com/microsoft/vcpkg/commit/0cf5b4305ba811d069d3ce328261eeb54bf61c3a

So, I'm not sure how to proceed. I have the file in disk, and it also exists in the commit from the remote repository. That error could be a red herring but I don't how to troubleshoot this.

**Comment by HexDecimal** [comment]
There was a regression with one of libtcod's dependencies so I had to use Vcpkg's versioning.  If your clone of the Vcpkg repo is too shallow then it will fail.  This error already tells you what to do:

> This may be fixed by updating vcpkg to the latest master via `git pull` or fetching commits via `git fetch`.

Run `git fetch --all` from the Vcpkg submodule directory then try again.

**Comment by HexDecimal** [comment]
I've updated the rules for libtcod's submodules so this won't happen again.  You won't need to perform this step the next time you clone the repository.

**Comment by ljfp** [comment]
Thanks! That was it. Somehow I had the idea that `git fetch --all` was the default behaviour of `git fetch` (hence, no need for an `--all` flag). After doing that, I was able to finish the configuration.
