### ISSUE TITLE
Printing API needs a rework.

### ISSUE THREAD

**Issue by HexDecimal** [libtcod/libtcod#129]
There are a lot of parameters that go into libtcod's printing API and there are many different functions handle the different combinations them.  I'd like to replace all these functions with a struct which contains any relevant arguments as parameters.

I'll be versioning these to preserve my sanity.
```c
typedef struct TCOD_PrintParams1 {
  ...
} TCOD_PrintParams1;

int TCOD_printf_1(TCOD_Console* console, const TCOD_PrintParams1* params, const char* fmt, ...);
int TCOD_printn_1(TCOD_Console* console, const TCOD_PrintParams1* params, int n, const char* str);
int TCOD_vprintf_1(TCOD_Console* console, const TCOD_PrintParams1* params, const char* fmt, va_list args);
```

```c
const TCOD_PrintParams1 params = {
    .x = 5;
    .y = 5;
    .fg = {255, 255, 0, 255};
};  // Yellow text with no background.
TCOD_printf_1(console, &params, "%s", "Hello World");
```

Having some kind of "style" struct for drawing functions and text might also help with this.

**Comment by hazeled** [comment]
I'd be happy to take this tonight if no one's started on it already

**Comment by HexDecimal** [comment]
I wouldn't mind.  It's mostly stalled because I keep coming back to how I should implement this system for regular drawing functions.  Which would help with how this should be done.

I also keep obsessing over implementing this wrong and being stuck with the API, even through there are easy solutions to that kind of issue.

It almost implements itself with the `struct PrintParams` struct in `console_printing.c`, I'm just not happy with that exact struct.

**Comment by HexDecimal** [comment]
In the end I'll be able to work with whatever you come up with.

**Comment by hazeled** [comment]
Sounds great!! I'll get started on this in a minute

**Comment by hazeled** [comment]
I see why you gave this one a minute. Deciding how to implement it definitely poses issues. I'm mostly done, but what would you think about adding a function to populate a "TCOD_PrintParams" struct? Maybe something like `TCOD_CreatePrintParams`? Allowing for things like alignment or bounding to be specified, but only optionally

**Comment by HexDecimal** [comment]
I'd want to make a struct which will have sane defaults when zero initialized, and can be aggregate initialized with the desired options.

If the struct would have bad attributes when zero initialized then the enums for those values should be changed.
A more complete example of my first code sample might look like this:
```cpp
typedef struct TCOD_PrintParams1 {
  int x;
  int y;
  int width;  // Unbound on zero.
  int height;
  int ch;
  TCOD_ColorRGB* fg;  // Skip color on nullptr.
  TCOD_ColorRGB* bg;
  TCOD_alignment_t alignment;
  TCOD_bkgnd_flag_t bg_flag;
} TCOD_PrintParams1;
```
`TCOD_bkgnd_flag_t` however has a bad default.

To call the function you could do something similar to:
```cpp
TCOD_printf_1(console, TCOD_PrintParams1{.x = 5, .y = 5, .fg = {255, 255, 255}}, "%s", "Hello World");
```

**Comment by HexDecimal** [comment]
So a function to populate this struct wouldn't do anything better than simply assigning to it,

**Comment by hazeled** [comment]
Haha, the struct I built is almost literally identical to the one you posted - down to the variable names. The only reason I suggested a function like that was because C doesn't support default zero-initialization. I suppose you can always just use `TCOD_PrintParams PrintParams = {0};`, though

**Comment by HexDecimal** [comment]
In C99 using designator expressions `{.x = 5}` will zero the remaining attributes.

**Comment by hazeled** [comment]
Oh my god, of course. I've been doing C and C++ for a while, that's just on me for forgetting something that basic. Anyways, PR'd at #132. I put it in console_printing but I'm not sure that's the best place for it, I'd be happy to restructure if you think it's better somewhere else
