### ISSUE TITLE
Problem with a 64 by 64 pixel font

### ISSUE THREAD

**Issue by l-t-m-f** [libtcod/libtcod#130]
Hello,

I am exploring the libtcod 1.22 release. The documentation is quite poor, and I'm using C.
So, I have some issue which only appears with a custom tileset which is 64 by 64 pixels. This issue is not present with the regular 16 by 16 tileset.

Basically, I am using the following line
TCOD_console_printn(cnsl, player->entity.base.x, player->entity.base.y, 1, "@", &TCOD_amber, &TCOD_black, 0, TCOD_LEFT);
(https://github.com/l-t-m-f/C_Libtcod_Roguelike/blob/main/src/entity.c)

Which works very fine except when my player is walking on the very last row of the map. If that's the case, I get a weird flickering of some tiles. These tiles will flicker to the player's "@" character...

I draw my stage using basic for loops : https://github.com/l-t-m-f/C_Libtcod_Roguelike/blob/main/src/stage.c

I have a feeling this is a memory issue, either something dumb I did or maybe something deeper, so I wanted to post this here to hopefully get some insights.

If I deactivate my tileset, the issue is not present.

My full code base:
https://github.com/l-t-m-f/C_Libtcod_Roguelike

**Comment by l-t-m-f** [comment]
I close this issue because as usual 5 minutes after posting I find the problem.
It was an old call I forgot to change to TCOD_console_put_char which I hear is deprecated now which was interacting badly.
I changed it to a TCOD_console_printf call and the glitch is gone.

**Comment by HexDecimal** [comment]
Your codebase is not publicity viewable.

`TCOD_console_put_char` and `TCOD_console_printf` should work as documented, even if `TCOD_console_put_char` is deprecated.  They don't have any known issues which can cause flickering.

Generally the renderers will show whatever is on the consoles when they are presented.  Any flickering is likely from your own drawing routine having flickering results, but to be sure you can use `TCOD_RENDERER_SDL2` as that's the most reliable renderer.

**Comment by l-t-m-f** [comment]
I made the code visible now.

It turns out I was making two **mistakes**.

Using char instead of char* was the first mistake.
I also didn't realize I had to call the character code by using the Array index (ie TCOD_CHARMAP_CP437[char_value] and not simply char_value). This caused me quite some pain as I was unable to render some characters for a while :p

**Comment by HexDecimal** [comment]
A common mistake.  Libtcod uses strict Unicode now so If you were using `char_value` thinking it was addressing the tile by a raw index (or by EASCII CP437) then you were actually addressing the `latin-1` block.

`TCOD_CHARMAP_CP437[eascii]` is a simple way to get the Unicode codepoint but using the codepoints directly is the best option.  You can also paste the glyphs (such as `"╬"`) into your strings and libtcod will know how to print them if your compiler is configured to use UTF-8.

Wikipedia is a good reference for the Unicode codepoints if you need them by number:
https://en.wikipedia.org/wiki/Code_page_437
`╬` would be `0x256C` for example.
