### ISSUE TITLE
How to use libtcod from vcpkg in 64bit MSVC project?

### ISSUE THREAD

**Issue by Aardvarklord** [libtcod/libtcod#135]
I have installed libtcod via vcpkg in Windows and use it in a cmake project in Visual Studio 2022. It works fine for an x86 build target, but for an x64 target I get  

>Error		CMake Error at D:/Programs/vcpkg2022/vcpkg/scripts/buildsystems/vcpkg.cmake:834 (_find_package):
>  Could not find a package configuration file provided by "libtcod" with any
>  of the following names:
>
>    libtcodConfig.cmake
>    libtcod-config.cmake
>
>  Add the installation prefix of "libtcod" to CMAKE_PREFIX_PATH or set
>  "libtcod_DIR" to a directory containing one of the above files.  If
>  "libtcod" provides a separate development package or SDK, be sure it has
>  been installed.		D:/Programs/vcpkg2022/vcpkg/scripts/buildsystems/vcpkg.cmake	834	
  
After installing libtcod with vcpkg, the only libtcod folder I have under vcpkg is  
vcpkg\packages\libtcod_x86-windows  
  
If I add the CMAKE variable "CMAKE_PREFIX_PATH": "D:/Programs/vcpkg2022/vcpkg/packages/libtcod_x86-windows" to the build target, I instead get  
  
>Error		CMake Error at D:/Programs/vcpkg2022/vcpkg/scripts/buildsystems/vcpkg.cmake:834 (_find_package):
>  Could not find a configuration file for package "libtcod" that is
>  compatible with requested version "".
>
>  The following configuration files were considered but not accepted:
>
>    D:/Programs/vcpkg2022/vcpkg/packages/libtcod_x86-windows/share/libtcod/libtcodConfig.cmake, version: 1.23.0 (32bit)		D:/Programs/vcpkg2022/vcpkg/scripts/buildsystems/vcpkg.cmake	834	
  
My CMakeLists.txt contains  
find_package(libtcod CONFIG REQUIRED)  
  
It seems to me the x64 build target rejects the only libtcod version I have since it is 32 bit. Is it expected that installing libtcod via vcpkg only provides a 32 bit version?

**Comment by Aardvarklord** [comment]
SOLVED  
  
Turned out the problem was my lack of vcpkg knowledge. Installing with 
  
vcpkg install libtcod:x64-windows  
  
provided the 64 bit version I needed for the x64 build target

**Comment by HexDecimal** [comment]
Vcpkg's Manifest Mode can help by selecting triplets automatically based on what's running CMake.  There's also an environment flag if you want 64-bit to be the default.
