### ISSUE TITLE
Confusing names of [l|m|r]button_pressed TCOD_mouse_t  properties

### ISSUE THREAD

**Issue by nataraj-hates-MS-for-stealing-github** [libtcod/libtcod#146]
Hi!
I was strongly confused by `lbutton_pressed` property of [TCOD_mouse_t](https://libtcod.readthedocs.io/en/latest/library/struct_t_c_o_d__mouse__t.html)

It's name says about button being pressed, but it is `true` when button is actually released (not pressed) while short or long click.

I think it might be good to do something about it. Like adding better named aliases, or renaming it...

**Comment by HexDecimal** [comment]
I'd have also assumed this was a on-mouse-down check.  Looking at the docs I can verify that it was always a click check, but the original docs were not so well written either:
```
	@Param lbutton_pressed true if the left button was pressed and released.
	@Param rbutton_pressed true if the right button was pressed and released.
	@Param mbutton_pressed true if the middle button was pressed and released.
```
I can't justify the breakage that'd come from renaming the attributes, almost the entire libtcod event system is already deprecated as-is, but I could at least move these docs into their proper place and clarify that this checks for a click.

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
Fixing doc also might help.

Thanks!
