### ISSUE TITLE
#include Header is incorrect in docs/guides/getting-started.md for the example main.cpp file.

### ISSUE THREAD

**Issue by deppong** [libtcod/libtcod#152]
**Describe the bug**
For including SDL2, the header file is <SDL.h>not <SDL2.h>

**To Reproduce**
Follow the steps provided in the tutorial, you will get build errors that say "SDL2.h" no such file or directory found"

**Expected behavior**
It should build and run properly!

**solution**
```cpp
//#include <SDL2.h>
#include <SDL.h>
#include <libtcod.hpp>

int main(int argc, char* argv[]) {
  auto console = tcod::Console{80, 25};  // Main console.
...
```

**Environment (please complete the following information):**
 - Platform: Artix Linux
 - Libtcod version: Current VCPKG build
 - Libtcod source: VCPKG
 - Compiler used: G++

**Additional context**
Please correct me if I'm wrong, but testing on Linux building this doesn't work unless I change SDL2.h to SDL.h. Once this is done and all other dependencies are installed, this tutorial works fantastically!

**Comment by HexDecimal** [comment]
You're correct on this. It's easy to mess up code examples. Thanks for reporting it.

**Comment by deppong** [comment]
No problem! I've made similar mistakes too! Thanks for correcting it so quickly!
