### ISSUE TITLE
Allow disabling CMake install targets

### ISSUE THREAD

**Issue by harryisgamer** [libtcod/libtcod#153]
**Is your feature request related to a problem? Please describe.**
I'm using libtcod with CMake's [FetchContent](https://cmake.org/cmake/help/latest/module/FetchContent.html) instead of vcpkg. Since version 3.24, CMake has support for `OVERRIDE_FIND_PACKAGE`, which allows for transitive dependencies in subprojects to resolve correctly without needing vcpkg or other package managers.

This _almost_ works with libtcod, but `OVERRIDE_FIND_PACKAGE` doesn't seem to work for `install(EXPORT)` targets, failing with this unfortunate error:
```
CMake Error: install(EXPORT "libtcodTargets" ...) includes target "libtcod" which requires target "SDL2" that is not in any export set.
CMake Error: install(EXPORT "libtcodTargets" ...) includes target "libtcod" which requires target "zlib" that is not in any export set.
```

I've been using this terrible hack to get around this:
```cmake
set(LIBTCOD_LODEPNG "vendored" CACHE STRING "")
set(LIBTCOD_UTF8PROC "vendored" CACHE STRING "")
set(LIBTCOD_STB "vendored" CACHE STRING "")
FetchContent_Declare(libtcod GIT_REPOSITORY https://github.com/libtcod/libtcod GIT_TAG 1.24.0)
FetchContent_GetProperties(libtcod)
if(NOT libtcod_POPULATED)
    FetchContent_Populate(libtcod) # Fetch libtcod
    
    # Delete libtcod's src/CMakeLists...
    file(REMOVE ${libtcod_SOURCE_DIR}/src/CMakeLists.txt) 
    # and replace it with a custom, patched CMakeLists.txt with the install() targets removed
    configure_file(libtcod_patch.txt ${libtcod_SOURCE_DIR}/src/CMakeLists.txt COPYONLY)
    
    add_subdirectory(${libtcod_SOURCE_DIR} ${libtcod_BINARY_DIR}) # Configure libtcod
endif()
```
This works, but requires manually updating the patched CMakeLists.txt if it ever changes.

**Describe the solution you'd like**
A CMake option to disable the install targets in `src/CMakeLists.txt`. Something like:
```cmake
# CMakeLists.txt, line 49
set(LIBTCOD_SAMPLES OFF CACHE BOOL "Build sources from the samples directory.")
set(LIBTCOD_TESTS OFF CACHE BOOL "Build unit tests.")
set(LIBTCOD_INSTALL ON CACHE BOOL "Enable install targets.")

# src/CMakeLists.txt, line 139
if(LIBTCOD_INSTALL)
    install(
         TARGETS ${PROJECT_NAME}
         EXPORT ${PROJECT_NAME}Targets
         RUNTIME LIBRARY ARCHIVE
         COMPONENT Library
    )
   
   # other install targets
endif()
```

**Describe alternatives you've considered**
- I'm currently patching libtcod's CMakeLists.txt after FetchContent downloads it, but this is annoying and unreliable across versions.
- I could just use vcpkg, libtcod's recommended package manager, but vcpkg has problems (and I don't really like it).

**Additional context**
Many other open source libraries that use CMake support disabling their install targets, such as [zlib](https://github.com/madler/zlib/blob/develop/CMakeLists.txt#L186) and [SDL](https://github.com/libsdl-org/SDL/blob/release-2.30.0/CMakeLists.txt#L401).

If anyone is interested, [here](https://gist.github.com/harryisgamer/627f7279887dffda76a4909e3f94a01f) is a full CMakeLists.txt that gets libtcod 1.24.0 to work with FetchContent.

**Comment by HexDecimal** [comment]
I'm assuming I disable that entire section of code, including package configuration since that's for `FindPackage` and not other forms of inclusion. Be sure to reopen this if the issue isn't resolved.

**Comment by harryisgamer** [comment]
I've tested this and it works with my project.
Here is an updated [example](https://gist.github.com/harryisgamer/3f6abf6422cdace833d313a1017cda2b) of using libtcod with FetchContent.

Thank you!

**Comment by HexDecimal** [comment]
Sounds great! Though it's a shame that multiple dependencies are still vendored, it's nice to see a real example of libtcod functioning with `FetchContent`.

**Comment by harryisgamer** [comment]
Personally, I prefer having those dependencies vendored. They (lodepng, utf8proc, and stb) are all either single-header or two-file dependencies, and vendoring them isn't a problem, at least for me.

That being said, I have put together an example of using libtcod with FetchContent and no vendored dependencies, available [here](https://gist.github.com/harryisgamer/b18385b1a2078d8c755e6612352b5a8b).

**Comment by HexDecimal** [comment]
Regardless. It was nice of you to show me an example using `FetchContent` for all dependencies. I hope I can make use of it later.
