### ISSUE TITLE
TCOD_FONT_TYPE_GREYSCALE is defined twice

### ISSUE THREAD

**Issue by ElectricCoffee** [libtcod/libtcod#21]
`TCOD_FONT_TYPE_GREYSCALE` in https://github.com/libtcod/libtcod/blob/master/src/libtcod/console_types.h is defined twice one after the other.
Is that intentional or a bug?

**Comment by HexDecimal** [comment]
It's intentional.  If you look closely it's actually both the US and UK variant of gray/grey which are defined instead of the same word.  I think it's been like this since the beginning.

Keep in mind that this flag isn't used anymore in the font loaders of the newer renderers (SDL2/OPENGL2).
