### ISSUE TITLE
Problems Compiling Under GNU/Linux x86-64

### ISSUE THREAD

**Issue by Andres6936** [libtcod/libtcod#24]
I tried to compile Libtcod and received the following errors:

```cxx
../../src/libtcod/sdl2/gl2_renderer.cpp:210:47: error: array must be initialized with a brace-enclosed initializer
   std::array<ptrdiff_t, 2> cached_size_{-1, -1};
                                               ^
../../src/libtcod/sdl2/gl2_renderer.cpp:210:47: error: too many initializers for ‘std::array<long int, 2ul>’
../../src/libtcod/sdl2/gl2_renderer.cpp:385:41: error: array must be initialized with a brace-enclosed initializer
   std::array<int, 2> cached_size_{-1, -1};
                                         ^
../../src/libtcod/sdl2/gl2_renderer.cpp:385:41: error: too many initializers for ‘std::array<int, 2ul>’
```

GNU/Linux version: 4.15.0-36-generic
Hardware Platform: x86-64
GCC version: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0
SDL version: 2.0.9

###### _Translated by Deepl_

**Comment by Andres6936** [comment]
I forgot, the steps I followed to compile the project are these:

https://github.com/libtcod/libtcod/tree/master/build/autotools

**Comment by HexDecimal** [comment]
I think this is a problem with older versions of GCC.  GCC 6.1 or later should fix it.

**Comment by HexDecimal** [comment]
You can install later versions of GCC on early versions of Ubuntu using this PPA:

https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test

Then tell Autotools to use the newer version of GCC.  One way would be to set environment variables such as `CC=gcc-6` and `CXX=g++-6`.

Sorry for the late clarification on this.

**Comment by Andres6936** [comment]
I'm so sorry for the delay.

Yes, the problem resides in the version of the compiler used, I have verified that it is possible to compile Libtcod in Ubuntu under the version of the compiler GCC 9.1.0.

Thank very much,

Close.
