### ISSUE TITLE
Please migrate build scripts to Python 3

### ISSUE THREAD

**Issue by FabianWolff** [libtcod/libtcod#29]
Python 2 will [reach its end-of-life](https://pythonclock.org/) soon. Therefore, some Linux distributions such as Debian have recently intensified their efforts to remove dependencies on Python 2, compare e. g. [Debian bug #936925](http://bugs.debian.org/936925) concerning the libtcod package.

The Python scripts in `build/autotools/` are still using Python 2; please migrate them to Python 3 (i. e., the first line should say `#!/usr/bin/env python3`, and maybe some minor adjustments in the code will be necessary (I haven't tried running them with Python 3 yet, but there should be no major issues)).

**Comment by vignesh96** [comment]
I will take a peek at it.

**Comment by HexDecimal** [comment]
PR #30 has been merged.

I'm kind of surprised that when someone looks at the Autotools build script the only problem they have is that it isn't explicitly using Python 3.  I usually feel like the Python scripts are hacked in currently.

@FabianWolff, does this need to be in a tagged release?

**Comment by FabianWolff** [comment]
> I'm kind of surprised that when someone looks at the Autotools build script the only problem they have is that it isn't explicitly using Python 3. I usually feel like the Python scripts are hacked in currently.

Opening this issue was a direct response to receiving the mentioned bug report in Debian. Maybe there are other issues; but this one was very concrete, somewhat important and especially easy to fix.

> @FabianWolff, does this need to be in a tagged release?

No. Thanks for suggesting it, but it's not urgent (and even if it was, I could just cherry-pick this change as a patch until the next libtcod release).
