### ISSUE TITLE
build.bat cannot find internal_function_teardown

### ISSUE THREAD

**Issue by JasonMarechal25** [libtcod/libtcod#31]
Hello
I've tried to run the build.bat script on Win10 but got an error "cannot find internal_function_teardown"

Full log bellow
`
>build.bat
'hg' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes

Usage: build.bat [OPTION]
    -fd, fetch-dependencies    download if necessary
    -pd, prepare-dependencies  extract and/or build, ready for project build
    -mr, make-release          construct release directory for packaging
    -pr, package-release       compress and archive release directory

    -d, dependencies           fetch and prepare the dependencies
    -p, project                build this project using the dependencies
    -r, release                construct/compress/archive built project
WARNING: 'hg.exe' cannot be located.  Mercurial may not be installed.
  This script can operate without it, but that mode is less supported.
  If Mercurial is not in PATH, you can set HG_EXE to full filename of 'hg.exe'

Le système ne trouve pas le nom de fichier de commandes - internal_function_teardown
`

**Comment by HexDecimal** [comment]
Thanks for the report.

I don't maintain the `build.bat` script, and I'm not sure if it's been tested on Windows 10 before.  I won't be able to fix this directly.

You can try building the library from `build/msvs` (recommended) or `build/scons`. If you just want the prebuilt library files then you can download those from the [GitHub release page](https://github.com/libtcod/libtcod/releases).

**Comment by jice-nospam** [comment]
I don't know how build.bat is working, but do you have mercurial (hg.exe) installed on your system and in the PATH ?

**Comment by JasonMarechal25** [comment]
@jice-nospam  I don't have mercurial but from my understanding the script should work without it.

@HexDecimal I wanted to have libtcod as a git submodule and build the library from my CMake project. For now I've resorted to use the prebuild libraries.

**Comment by HexDecimal** [comment]
I'd like to add CMake files to make that kind of thing easier, but I have trouble with handling SDL2 as a library dependency.
