### ISSUE TITLE
Problem with TCOD_NODISCARD

### ISSUE THREAD

**Issue by sbowman** [libtcod/libtcod#36]
In trying to compile an app with libtcod 1.15.1 on macOS (Mojave and Catalina), I'm getting an error with the `TCOD_NODISCARD` values everywhere.  I believe it's an incompatibility with clang.

   libtcod/sys.h:58:17: error: 'nodiscard' attribute cannot be applied to types TCODLIB_API int TCOD_NODISCARD TCOD_sys_set_renderer(TCOD_renderer_t renderer);

    libtcod/engine/display.h:195:14: error: an attribute list cannot appear here TCODLIB_CAPI TCOD_NODISCARD int TCOD_console_init_root(

    libtcod/engine/display.h:197:14: error: an attribute list cannot appear here TCODLIB_CAPI TCOD_NODISCARD int TCOD_console_init_root_(

    libtcod/engine/display.h:281:14: error: an attribute list cannot appear here TCODLIB_CAPI TCOD_NODISCARD int TCOD_sys_init_sdl2_renderer_(

A quick fix for this is to simply disable TCOD_NODISCARD for clang in portability.h (line 201):

    #if !defined(__clang__) && defined(__cplusplus) && __cplusplus >= 201703L

I'm not a great C++ programmer, but I think the correct fix is to move TCOD_NODISCARD before TCODLIB_CAPI in each of the above lines.  At least, this worked on macOS.  I don't know what it does to other compilers.

**Comment by HexDecimal** [comment]
The current tests for Xcode11 seem to work: https://travis-ci.org/libtcod/libtcod/jobs/618817625
I haven't gotten around to running these tests on older versions yet.

Can you tell me what your versions of Xcode and Clang are?

**Comment by sbowman** [comment]
I'm running Catalina 10.15.1, with Xcode 11.2.1 installed.  I'm building my app with CLion 2019.3, using the following clang:

    Apple clang version 11.0.0 (clang-1100.0.33.12)
    Target: x86_64-apple-darwin19.0.0
    Thread model: posix

**Comment by sbowman** [comment]
I looked at the Travis output.  Is it compiling with C++ 14, rather than 17 (`compiler.cppstd=14`)?  Since [[nodiscard]] is a C++ 17 feature, I'm assuming C++ 14 defaults into a blank TCOD_NODISCARD value, which is why it compiles successfully in Travis.

I've got CMake configured to use C++ 17.

**Comment by HexDecimal** [comment]
Thanks for looking at the logs and pointing out the C++14/C++17 distintion.  I hoped that the config headers were forward compatible but clearly they're not.

I'll implement the quick fix then.  Clang has `__GNUC__` defined so it will end up using `__attribute__ ((warn_unused_result))` which it seems to be okay with.
