### ISSUE TITLE
Remove C++ dependencies.

### ISSUE THREAD

**Issue by HexDecimal** [libtcod/libtcod#39]
As much as I liked using C++ over C it has made the code less portable and made the C ABI harder to maintain.  I now plan on rewriting the code in C and porting to C++ instead of the other way around.

The following needs to be rewritten in C:
- [x] New tileset objects.
- [x] Tileset font loader.
- [x] TrueType font loader.
- [x] SDL2 renderer.
- [x] OpenGL2 renderer.
- [x] Libtcod initialization.
- [x] Console UTF-8 functions.
- [x] Console drawing functions.
- [x] Console initialization.
- [x] Image functions.
- [x] Event functions.
- [x] System functions.
- [x] Compile without C++.

**Comment by tanis2000** [comment]
This would definitely help in supporting emscripten/wasm too. What's your ETA on this?

**Comment by HexDecimal** [comment]
I thought Emscripten could compile C++.  If anything currently prevents an emscripten/wasm build then feel free to create an issue for it.

Some of the refactoring is hard to do since a lot of the rendering functions depend on each other, so those all have to be done at once before I can test and upload it.

No real ETA, but I'm trying to get as much as I can done before the February 7DRL.  This _might_ be done before the end of January, but there will still be a lot of compiled C++ code left over after this task is done.

**Comment by tanis2000** [comment]
Emscripten can compile C++ but it’s a bit of a mess when there are external libraries and C++14 involved.

Some standard libraries like zlib and SDL2 have already been ported but others like GLAD and probably others would need to be ported manually.

The best would be to reduce the number of external dependencies to the bare minimum.

On top of that, a port to pure C would be nice for people like me that usually avoid C++

**Comment by HexDecimal** [comment]
GLAD is for the desktop builds, and it keeps the function names standard so that I can switch between OpenGL and OpenGLES easier.  I just need to add the preprocessor code that actually does that.

**Comment by HexDecimal** [comment]
It's done, all the major components compile and run without the C++ sources.  Right now it's only python-tcod which is setup to compile without C++.

I want to test Emscripten but I've been unable to setup the tool-chain so far.  I expect it to fail, and that I'll need to switch the headers to use GLES.  That kind of thing will be tracked in issue #41 if I make more progress.

**Comment by tanis2000** [comment]
Nice! ;)
