### ISSUE TITLE
is this correct

### ISSUE THREAD

**Issue by SHADOWELITE7** [libtcod/libtcod#4]
I am planning to make a roguelike but before I do that, I looked at the Readme and it said I am required to have this `` Visual Studio 2015 runtimes``. Is ``Microsoft Visual C++ 2015 Redistributable (x64) -14.0.24215`` the same thing?

**Comment by HexDecimal** [comment]
That version will work as long as your Python installation is also 64-bit.

**Comment by SHADOWELITE7** [comment]
ok thank you
