### ISSUE TITLE
Linker Errors compiling 1.16.0.alpha 8 Samples

### ISSUE THREAD

**Issue by davemoore22** [libtcod/libtcod#49]
On Ubuntu 18.0.4, trying to compile/link (using the autotools method) 1.16.0.alpha 8 I get the following linker errors linking the samples, which I believe is something to do with the version of SDL2 I have installed (according to https://askubuntu.com/questions/1160697/undefined-reference-when-using-sdl-ttf).

```
CCLD     samples_c
./.libs/libtcod.so: undefined reference to `SDL_RWclose'
./.libs/libtcod.so: undefined reference to `SDL_RWwrite'
./.libs/libtcod.so: undefined reference to `SDL_RWread'
./.libs/libtcod.so: undefined reference to `SDL_RWtell'
./.libs/libtcod.so: undefined reference to `SDL_RWseek'
collect2: error: ld returned 1 exit status
Makefile:1378: recipe for target 'samples_c' failed

```

The output of _dpkg -l | grep sdl2_ is:
```

dpkg -l | grep sdl2
ii  libsdl2-2.0-0:amd64                                              2.0.10+dfsg1-2ubuntu5~ubuntu18.04.1~ppa1         amd64        Simple DirectMedia Layer
ii  libsdl2-2.0-0:i386                                               2.0.10+dfsg1-2ubuntu5~ubuntu18.04.1~ppa1         i386         Simple DirectMedia Layer
ii  libsdl2-dev:amd64                                                2.0.10+dfsg1-2ubuntu5~ubuntu18.04.1~ppa1         amd64        Simple DirectMedia Layer development files
ii  libsdl2-image-2.0-0:amd64                                        2.0.3+dfsg1-1                                    amd64        Image loading library for Simple DirectMedia Layer 2, libraries
ii  libsdl2-image-dev:amd64                                          2.0.3+dfsg1-1                                    amd64        Image loading library for Simple DirectMedia Layer 2, development files
ii  libsdl2-mixer-2.0-0:amd64                                        2.0.2+dfsg1-2                                    amd64        Mixer library for Simple DirectMedia Layer 2, libraries
ii  libsdl2-mixer-dev:amd64                                          2.0.2+dfsg1-2                                    amd64        Mixer library for Simple DirectMedia Layer 2, development files
ii  libsdl2-ttf-2.0-0:amd64                                          2.0.14+dfsg1-2                                   amd64        TrueType Font library for Simple DirectMedia Layer 2, libraries
ii  libsdl2-ttf-dev:amd64                                            2.0.14+dfsg1-2                                   amd64        TrueType Font library for Simple DirectMedia Layer 2, development files

```

The same error happens when trying to compile 1.15.1.  Compiler versions I'm using for info:

```
gcc --version
gcc (Ubuntu 9.2.1-17ubuntu1~18.04.1) 9.2.1 20191102
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

g++ --version
g++ (Ubuntu 9.2.1-17ubuntu1~18.04.1) 9.2.1 20191102
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

D.

**Comment by HexDecimal** [comment]
As far as I can tell you are including the SDL 2.0.10 headers, which turn symbols like `SDL_RWclose` into functions, but then you might be linking an earlier version of SDL which only as them as macros.  That's the main way you'd get this error.

I'm not sure how to debug this, but there's [this post](https://steamcommunity.com/app/221410/discussions/0/1640915206461789705/#c1640915206462380264) showing how to manually check for the functions.  I'd make sure there isn't a second installation of SDL somewhere and that the main one you have has those symbols as functions.

**Comment by davemoore22** [comment]
Yes, that was the direct issue indeed!

Old versions of SDL2 installed. Removed those, cleaned all SDL2 up, and reinstalled SDL2, and it compiled. But oddly enough, it now fails to link in both scons _and_ autotools with this weird linking error.

```
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libSDL2.a(SDL_waylandvideo.o): relocation R_X86_64_PC32 against symbol `wl_registry_interface' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
scons: *** [libtcod-1.16.0-alpha.8-x86_64-DEBUG/libtcod.so] Error 1
scons: building terminated because of errors.
```
This seems to be, from my understanding, a mismatch in compiler options between SDL2 and libtcod, specifically hardening? I don't know enough scons however to adjust the compiler options.

**Comment by HexDecimal** [comment]
I'd guess you only compiled a static library version of SDL2 instead of a shared object.  SCons and Autotools need to link to an `.so` file, not an `.a` file (but it might work anyway if the file was compiled with `-fPIC` since the compiler is complaining about that. Statically linking SDL2 is actively discouraged by the SDL developers.)  Only the Conan builder has known support for statically linking libtcod itself.

Normally you just get the `libsdl2-dev` package from APT and have that be the only installation on your system.  That's the setup the works for most users.

**Comment by davemoore22** [comment]
Yeah, that's what I did. I wiped my system clean of sdl2 and then installed:

`libsdl2-2.0-0 libsdl2-dev libsdl2-image-2.0.0 libsdl2-image-dev libsdl2-mixer-2.0-0 libsdl2-mixer-dev libsdl2-ttf-2.0-0 libsdl2-ttf-dev
`
Does the order of installation count?

**Comment by HexDecimal** [comment]
For SDL, libtcod only requires the `libsdl2-2.0-0 libsdl2-dev` packages.  The installation order of APT packages doesn't matter, but if you manually installed SDL then it could have messed with the files installed by APT depending on how you installed it.

I'm not sure how much more I can help since I can't explain why libtcod is trying to link to `libSDL2.a` instead of the `.so` files.  Static linking is usually an option you have to enable as far as I know, unless the shared object is missing or something.

Another option might be to make sure that `libsdl2-dev` is removed and then only use a manually installed version of SDL2.

**Comment by davemoore22** [comment]
Alright, I'll take a stab at wiping SDL entirely from my system and retrying it.

Oddly enough, my previous installation, of 1.14 worked fine.

Thank you for your patience, I'm eager to get back into Libtcod and to use the new SDL surface handling functionality! Please keep up the good work with the library, it is really appreciated.

**Comment by davemoore22** [comment]
Ok, update, got it working. Bit of an involved saga at my end, but think probably mostly my fault.

Turns out my distribution (it is meant to be Xubuntu 18) had been in a half-upgraded state (and had been for the last year), so I went ahead and finished the upgrade. I then wiped SDL2 completely from my system. 

I then reinstalled SDL2 via apt as usual, and and a result all releases, including 1.15.1 and the various 1.16.alpha compile properly and run with a few minor caveats:

- I had made a small hack to makefile (in my case `makefile.am` in autotools) to add `-I/usr/include/SDL2` as on my system the SDL2 header libraries are installed into `/usr/include/SDL2`.
- The fonts are bit off in 1.16.alpha.* (see screenshot below), but I understand you're currently working on this area. The SDL Callback works in both SDL and SDL2 renderer.
- In 1.15.1, the fonts work fine with the SDL2 and OPENGL2, and fail on other renderers as SDL can't load `data/fonts/consolas10x10_gs_tc.png`(I'm running the samples from the `/buildsys/autotools` directory as directed in the documentation).
- Also in 1.15.1, the SDL Callback segfaults in SDL2, and haven't been able to test it in SDL. Again, I know you're working on this area.

![Screenshot_2020-05-10_22-31-39](https://user-images.githubusercontent.com/48893555/81511002-11761d00-930e-11ea-8a11-71000204cec0.png)

Hope this helps

**Comment by HexDecimal** [comment]
> I had made a small hack to makefile (in my case makefile.am in autotools) to add -I/usr/include/SDL2 as on my system the SDL2 header libraries are installed into /usr/include/SDL2.

Autotools should be using `sdl-config` to set these flags.

> The fonts are bit off in 1.16.alpha.* (see screenshot below)

Looks like an issue in the TTF loader used by the fallback font loader.  This was a known problem in older versions.  Always use the latest alpha release, or ideally use the develop branch, before reporting issues with the samples.

If this is from the develop branch then post the Git revision to avoid confusion.

> In 1.15.1, the fonts work fine with the SDL2 and OPENGL2, and fail on other renderers as SDL can't load data/fonts/consolas10x10_gs_tc.png(I'm running the samples from the /buildsys/autotools directory as directed in the documentation).

The documentation is likely outdated.  Something would be need to changed here but I'm not sure what.  I usually don't run the samples or unit tests from the Autotools builds.

> SDL Callback

This callback is deprecated and has been replaced by a few other functions in the alpha builds.  I have it working but it will perform slowly compared to the other methods.  It exists only for backwards compatibility.

**Comment by davemoore22** [comment]
OK, turns out that this path thing is  just a weird thing with some distributions - sdl2config reports on where it thinks it is installed by standard, not where it actually is. This is nothing that can't be fixed with adjusting includes and stuff so I'm happy for this to be closed. The weird linking errors are now gone since I did a reinstall.
