### ISSUE TITLE
OSx pkg-config fails

### ISSUE THREAD

**Issue by MichaelMackus** [libtcod/libtcod#57]
Hello,

A minor issue I noticed after building with autotools is the following error when invoking pkg-config with the --cflags option:

```
pkg-config libtcod --cflags
Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing `x11.pc'
to the PKG_CONFIG_PATH environment variable
Package 'x11', required by 'libtcod', not found
```

If I manually include the cflags into my project (which just consist of the SDL2 & libtcod include headers), the samples compile just fine. This leads me to believe x11 actually isn't required (at least for MacOSx).

**Comment by HexDecimal** [comment]
Oh yikes, an X11 dependency ended up on MacOS.  I'm not sure how much libtcod is using X11 right now as I've been trying to get rid of these platform specific dependencies forever.

Could try to just take x11 out of libtcod.pc.in: https://github.com/libtcod/libtcod/blob/e58912f8f5c20fa3bee990dc2d6145fe48cd0d85/buildsys/autotools/libtcod.pc.in#L9

And if that causes problems I'll modify libtcod to fix them if I can.

**Comment by HexDecimal** [comment]
I removed the X11 requirement from Autotools on the develop branch.  Everything looks good so far.

Any other issues?

**Comment by MichaelMackus** [comment]
This seems to work perfectly now, thank you for all the help!
