### ISSUE TITLE
Unable to run lua sample with error

### ISSUE THREAD

**Issue by ryanford** [libtcod/libtcod#6]
```
lua: libtcodlua.lua:11: attempt to call global 'a' (a nil value)
stack traceback:
	libtcodlua.lua:11: in main chunk
	[C]: in function 'dofile'
	samples_lua.lua:2: in main chunk
	[C]: ?
```

Compiled libtcod from source from this repo, version 1.10.2 built following autotools intructions on (l)ubuntu bionic beaver. Using Lua 5.1.5

**Comment by HexDecimal** [comment]
I finally found the original Lua build instructions: http://roguecentral.org/doryen/forum/index.php?topic=632.0

The DLL needs to be built using SWIG with Lua support enabled, then it can be imported by the `libtcodlua.lua` wrapper.  Right now this has to be done manually.

Direct ports of the libtcod API to scripting languages are a low priority for me, these types of ports have unavoidable performance issues for the more data-based parts of the API.

**Comment by HexDecimal** [comment]
I've decided that I'm going to drop support for Lua entirely.  A SWIG wrapper not a good way to make a high quality port.  Libtcod is too data focused to make a straight port into a scripting language without suffering from severe performance bottlenecks.

Anyone wanting to use Lua should look for something designed for it such as [T-Engine4](https://te4.org/te4).

Alternatively, use libtcod/C++ and emend Lua there to add scripting to your C++ programs.  Then you have both languages to use for whatever's appropriate for the task.
