### ISSUE TITLE
Add support for Vcpkg.

### ISSUE THREAD

**Issue by HexDecimal** [libtcod/libtcod#63]
https://github.com/Microsoft/vcpkg

Stuff related with CMake has already been setup when Conan support was added, those files should be modified to accept Vcpkg as well.

**Comment by HexDecimal** [comment]
The CMake files have been updated to support Vcpkg.

The following files will need to be tweaked, then added to `vcpkg/ports/libtcod` in the [vcpkg repo](https://github.com/microsoft/vcpkg) or your own local fork.

`ports/libtcod/CONTROL`:
```
Source: libtcod
Version: 1.16.0-alpha.10
Homepage: https://github.com/libtcod/libtcod
Description: a free, fast, portable and uncomplicated API for roguelike developers providing an advanced true color console, input, and lots of other utilities frequently used in roguelikes.
Build-Depends: sdl2, zlib
```

`ports/libtcod/portfile.cmake` (the next release after `1.16.0-alpha.10` will be supported):
```cmake
include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO libtcod/libtcod
    REF 1.16.0-alpha.10
    SHA512 a169659a8f576fb3096d8cea88d1873a35bc922433727c652fcb969169937af4107214e1c3b01424c91d52424a6396b947105db3f9092453a37104c0acc884e0
    HEAD_REF develop
)

vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}/src
    PREFER_NINJA
    OPTIONS ${FEATURE_OPTIONS} -DCMAKE_INSTALL_INCLUDEDIR=${CURRENT_PACKAGES_DIR}/include
)

vcpkg_install_cmake()

vcpkg_copy_pdbs()

file(INSTALL
    ${SOURCE_PATH}/LICENSE.txt
    DESTINATION ${CURRENT_PACKAGES_DIR}/share/libtcod RENAME copyright)

#vcpkg_test_cmake(PACKAGE_NAME LIBTCOD MODULE)
```

In its current state you can manually add these files and run `vcpkg install --head libtcod` to install from the develop branch.

**Comment by Andres6936** [comment]
_Did you know that you can simplify the dependency process with the [CPM](https://github.com/TheLartians/CPM.cmake) script?_

**Comment by HexDecimal** [comment]
CPM would have been nice to know about.  I might need to create an issue to keep track of it.
