### ISSUE TITLE
SDL2 2.0.12 fails with "No available video device"

### ISSUE THREAD

**Issue by char32** [libtcod/libtcod#67]
Hi,
I just did set-up a new project, built with conan which pulls SDL2 in version 2.0.12.
I use libtcod v1.16.0-alpha.12 from https://bintray.com/hexdecimal/conan/libtcod%3Ahexdecimal (via conan too).

It builds fine, but whenever I want to start the application I get:
terminate called after throwing an instance of 'std::runtime_error'
  what():  libtcod 1.16.0-alpha.12 /build/.conan/data/libtcod/1.16.0-alpha.12/hexdecimal/stable/build/0ef918539b619597dc39f7f04ca3684886ea676a/src/libtcod/renderer_sdl2.c:621
Could not initialize SDL:
No available video device
Aborted (core dumped)

Seems like problem with the latest SDL2?

**Comment by HexDecimal** [comment]
I'm not sure if this is an issue with SDL2 or your platform.  If it was the SDL version then you could tell Conan to get a different one.

What is your OS?

**Comment by char32** [comment]
Indeed, it was the SDL2 version! Thank you very much!
conan was told to ~= take v2.0.5 - so it did take the recent one which is 2.0.12. As I changed it to explicitly take 2.0.9 it worked.

I found out there is is a known SDL2 bug (just for the conan version) for SDL2 > 2.0.9 that causes the issue. It is this one: https://github.com/bincrafters/community/issues/1121

Btw. my OS is Linux Mint 19.3 (based on Ubuntu 18.04).

So I think it's no bug in libtcod :-) We can close this I guess.

**Comment by HexDecimal** [comment]
I think you've made a pretty good explanation of the problem and how to work around it.

I'll keep this issue up and close it once things are fixed upstream.

**Comment by Andres6936** [comment]
The same problem occurred with this [Pull Request](https://github.com/libtcod/libtcod/pull/64)

**Comment by HexDecimal** [comment]
Conan just breaks upstream sometimes, not just with SDL video device issues but sometimes it won't be able to compile at all on some platforms for several days.

The only real long term solution would be to ensure there's alternatives to Conan, but I've had similar troubles with Vcpkg too.

**Comment by Croydon** [comment]
> Conan just breaks upstream sometimes, not just with SDL video device issues but sometimes it won't be able to compile at all on some platforms for several days.

A lot of parts are still moving around pretty quickly in Conan and Conan recipes. Once we reach 2.0 things should get much calmer.

That said, if you want to ensure absolute stability you need to pin specific revisions https://docs.conan.io/en/latest/versioning/revisions.html

___________

IIRC the problem in the SDL2 recipe should be solved for a while now. Could anyone of you please re-try? Please make sure that your local copy of the recipe is actually up-to-date. Either remove your local version(s) first or use `conan install  (...) --update` or similar

Thanks!

**Comment by HexDecimal** [comment]
The upstream issue has been closed.
