### ISSUE TITLE
Corrupt text when running samples_c.c

### ISSUE THREAD

**Issue by jmz-b** [libtcod/libtcod#68]
Hi, I'm currently trying to get set up for libtcod development on Ubuntu 20.04. After installing I built and ran `samples/samples_c.c` and got the following result:

![Screenshot from 2020-07-02 15-33-24](https://user-images.githubusercontent.com/9866884/86366376-050da100-bc7b-11ea-9481-9289460c5d73.png)
![Screenshot from 2020-07-02 15-48-02](https://user-images.githubusercontent.com/9866884/86366790-7f3e2580-bc7b-11ea-9ac2-f4c5f95e745e.png)
![Screenshot from 2020-07-02 15-48-07](https://user-images.githubusercontent.com/9866884/86366792-806f5280-bc7b-11ea-9b2e-a3fcb908df07.png)

I built and installed libtcod using autotools as described [here](https://github.com/libtcod/libtcod/blob/develop/buildsys/autotools/README.md)

I built sample_c.c with the following command:

```
gcc samples_c.c `pkg-config libtcod --cflags --libs` `sdl2-config --cflags` `sdl2-config --libs` -lm
```

anyone have any idea what is going on here?

**Comment by jmz-b** [comment]
Fixed, I had to move the compiled executable up a directory so the hardcoded relative path on the following line was correct:

```
        char *font="data/fonts/dejavu10x10_gs_tc.png";
```

**Comment by jmz-b** [comment]
Fixed, I had to move the compiled executable up a directory so the hardcoded relative path on the following line was correct:

```
        char *font="data/fonts/dejavu10x10_gs_tc.png";
```

**Comment by HexDecimal** [comment]
Which version of libtcod was used?  I assume it was probably `1.15.1` but it's recommended to be using the latest alpha on the master branch.

**Comment by jmz-b** [comment]
This was on `1.16.0-alpha.12`
