### ISSUE TITLE
saved images are shades of red

### ISSUE THREAD

**Issue by LordKaT** [libtcod/libtcod#70]
Whether manually placing pixels with TCODImage::putPixel and using TCODImage::save or using TCODSystem::save_screenshort, or feeding the console directly to TCODImage, the output is always red-scale.

64-bit Windows 10, compiling 32-bit across libtcod and main project. If I'm doing something wrong please feel free to yell ;)

![test](https://user-images.githubusercontent.com/1979210/87246972-d5029280-c41e-11ea-841f-e0a86530796f.png)

**Comment by HexDecimal** [comment]
Do you have any code examples?

You do get similar results from running the libtcod samples?  (PrtScn to save a screenshot.)

Are you using the latest alpha version?

**Comment by LordKaT** [comment]
@HexDecimal I'm on 1.16.0 alpha 12, x86

Here's the code I'm using the generate the image:

`
TCODImage* worldimage = new TOCDImage(WORLDSIZE, WORLDSIZE);
	for (int y = 0; y < WORLDSIZE; y++) {
		for (int x = 0; x < WORLDSIZE; x++) {
			//this->iWorldMap[y * WORLDSIZE + x] = (perlinmap[y * WORLDSIZE + x] * (particlemap[y * WORLDSIZE + x]) / 255);
			this->iWorldMap[y * WORLDSIZE + x] = perlinmap[y * WORLDSIZE + x];
			if (this->iWorldMap[y * WORLDSIZE + x] > 255) this->iWorldMap[y * WORLDSIZE + x] = 255;

			int r = 0, g = 0, b = 0;
			/*
			if (this->iWorldMap[y * WORLDSIZE + x] < 10)
				b = 127 - this->iWorldMap[y * WORLDSIZE + x];
			else if (this->iWorldMap[y * WORLDSIZE + x] < 30)
				b = 225 + this->iWorldMap[y * WORLDSIZE + x];
			else {
			*/
				r = this->iWorldMap[y * WORLDSIZE + x];
				g = this->iWorldMap[y * WORLDSIZE + x];
				b = this->iWorldMap[y * WORLDSIZE + x];
			//}
			if (r < 0) r = 0;
			if (r > 255) r = 255;
			if (g < 0) g = 0;
			if (g > 255) g = 255;
			if (b < 0) b = 0;
			if (b > 255) b = 255;
			worldimage->putPixel(x, y, TCODColor(r, g, b));
		}
	}
	worldimage->save("test.bmp");
`

**Comment by l4tte** [comment]
Just tried it out myself. Can confirm the code does produce red images even when the `r`, `g`, and `b` values are equal. I'll look into this and submit a pr if I can find a fix

**Comment by l4tte** [comment]
I'm fairly certain this is an issue with TCOD_sys_create_bitmap, and probably the fmt variable, specifically the masking

**Comment by l4tte** [comment]
Actually maybe not, it might be before that. I'm close to fixing it, give me some time and I'll submit a PR. @HexDecimal I think I'll be done with this soon but if not feel free to assign it to me
