### ISSUE TITLE
Is there no way to use ttf files in C++ ?

### ISSUE THREAD

**Issue by l4tte** [libtcod/libtcod#73]
Hey! I've been looking at the docs and I see there are ways to use TTF files in python, but I can't seem to find an equivalent in C++. Is it possible and the docs are not listed because they're not finished? Thanks!

**Comment by HexDecimal** [comment]
The TTF functions are in C and are documented [here](https://github.com/libtcod/libtcod/blob/develop/src/libtcod/tileset_truetype.h).  They're not in the stable API yet.  You'll want to use the latest alpha version of libtcod or build it from the develop branch directly.

Right now `TCOD_tileset_load_truetype_` can be used to replace `TCODConsole::setCustomFont` until the API becomes more stable.
