### ISSUE TITLE
Possible issue in fov raycasting algorithm

### ISSUE THREAD

**Issue by piterlouis** [libtcod/libtcod#77]
Maybe I'm totally wrong, so take it only as a suggestion for checking ;). 

I think there's an issue in the implementation of the FOV algorithm with ray casting. In the file _fov_circular_raycasting.c_, in function _TCOD_map_compute_fov_circular_raycasting()_, when we are casting rays to the different quad sectors, the last ones are like this:

```
  xo = xmax - 2;
  yo = ymax - 1;
  while (xo >= 0) {
    cast_ray(m, player_x, player_y, xo--, yo, r2, light_walls);
  }
  xo = xmin;
  yo = ymax - 2;
  while (yo > 0) {
    cast_ray(m, player_x, player_y, xo, yo--, r2, light_walls);
  }
```

My doubt is if the condition of the whiles shouldn't be (x0 >= xmin) and (y0 > ymin)?. Like is now, I think extra unnecessary calculations are performed.

**Comment by HexDecimal** [comment]
It's possible.

Unnecessary code like this would be undetected for normal use.  My reviews of the FOV code have been more focused on reentrancy issues rather than of-by-one errors like this one.

I don't know the details of this implementation, but I assume something will need to cast to the cardinal directions.  I'll need to check if that's the case.

**Comment by HexDecimal** [comment]
I misinterpreted what you said at first.  I was able to test the changes you suggested and a casual observation of the FOV samples shows that it still works as expected.

The excess raycasts were being restricted by radius, which is way this wasn't noticed sooner.

**Comment by piterlouis** [comment]
Yes, it was a performance issue more than something not working correctly. As you said, the radius was limiting the area, but now, no extra calculations are performed, so would be way better.

Thank you for adding the fix!
