### ISSUE TITLE
Build Error on Debian Linux with gcc 8

### ISSUE THREAD

**Issue by jpuertos** [libtcod/libtcod#84]
On a Debian system attempting to build the package (with gcc-8) from the sources provided by conan (https://bintray.com/hexdecimal/conan/libtcod%3Ahexdecimal#) I get the following errors:

```
[ 94%] Building CXX object src/CMakeFiles/LIBTCOD.dir/libtcod/sdl2/event.cpp.o
[ 95%] Building C object src/CMakeFiles/LIBTCOD.dir/vendor/glad.c.o
In file included from /home/feanor/.conan/data/libtcod/1.16.0-alpha.15/hexdecimal/stable/build/299575996252ec376bd6f3337747144b11181acb/src/libtcod/pathfinding/astar.cpp:32:
/home/feanor/.conan/data/libtcod/1.16.0-alpha.15/hexdecimal/stable/build/299575996252ec376bd6f3337747144b11181acb/src/libtcod/pathfinding/astar.h: In function ‘void tcod::pathfinding::astar(DistMatrix&, const Graph&, const IndexType&)’:
/home/feanor/.conan/data/libtcod/1.16.0-alpha.15/hexdecimal/stable/build/299575996252ec376bd6f3337747144b11181acb/src/libtcod/pathfinding/astar.h:90:25: error: use of ‘auto’ in lambda parameter declaration only available with -std=c++14 or -std=gnu++14
   auto on_new_edge = [](auto, auto) {};
                         ^~~~
```
With many other errors for the same reason following.

My conan profile is the one below:

```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=8
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]

```
Is the c++ "std" specification missing in the CMake file? If only required for gcc would be nice if you added it.

**Comment by jpuertos** [comment]
Seems that perhaps you only need to update the 'target_compile_features' to haveC++14, in line 17 of CMakeLists.txt try putting:

`target_compile_features(LIBTCOD PUBLIC c_std_99 cxx_std_14)`

**Comment by HexDecimal** [comment]
All of the C++ source files like in `src/libtcod/pathfinder` are to be removed.  A lot of it was an experiment that didn't work out, so I could just switch all of my build jobs to enforce C++11 and remove anything which doesn't compile.

**Comment by HexDecimal** [comment]
`src/libtcod/pathfinder` has been removed from the `develop` branch.

I tried to set all of the build tools to C++11 but because the testing uses C++14 it's too difficult to set them up that way at the moment.  I'm not certain how Autotools could be set up to compile only the test executable in C++14 for example.

**Comment by HexDecimal** [comment]
Support for C++11 has been dropped.  C++14 is required at the moment, but C++17 is highly recommended.
