### ISSUE TITLE
Wrong characters when using print/printf using default font

### ISSUE THREAD

**Issue by jpuertos** [libtcod/libtcod#89]
C++, Linux, version 1.16.0-alpha.15: I try to print some strings (English text) using print/printf from "std::string" but many characters are missing (empty spaces?) and some others are printed with wrong ascii characters. This happens also if I use "const char*" literals like "Activity Log" for example. 'a' may be printed depending on the character that precedes it, if 'W' it won't show, but if preceded by 'E' yes.

I am using default font, have not touched anything related to font config.

What am I doing wrong?

**Comment by HexDecimal** [comment]
You'll need to include an example.  Keep in mind that the older deprecated functions will expect EASCII encoded strings while newer ones will expect UTF-8 encoded strings.  In either case ASCII-only strings shouldn't break the encoding.

**Comment by jpuertos** [comment]
```
TCODConsole::root->setBackgroundFlag(TCOD_BKGND_SET);
TCODConsole::setColorControl(TCOD_COLCTRL_1, _colors.fg, _colors.bg);
TCODConsole::root->printf(_pos.x, _pos.y, "%cActivity log%c", TCOD_COLCTRL_1, TCOD_COLCTRL_STOP);
```

This prints some garbage... and many missing characters.

**Comment by jpuertos** [comment]
This also happens when printing without the color control.

**Comment by HexDecimal** [comment]
Incorrect or missing ASCII characters implies that the font was loaded incorrectly.  I imagine that if you read the console characters directly they'll be correct.

Can you post which font you used and what parameters you loaded it with?  What libtcod is doing might not be obvious.

**Comment by jpuertos** [comment]
I am not doing anything related to font management in my code. BTW where can I find high res fonts for libtcod? not much luck with google

**Comment by HexDecimal** [comment]
Not using any font management is also notable.  What happens depends on how you initialize libtcod.  Automatically loading fonts is discouraged right now for different reasons depending on which auto-loader was used.

For very high-res fonts libtcod has a TTF loader which creates rather poor looking tilesets.  Libtcod works well with CP437 tilesets like in the [Dwarf Fortress tileset repository](https://dwarffortresswiki.org/index.php/Tileset_repository) or the PDCurses fonts.  BDF fonts also work partially and usually have better Unicode support.  These raster fonts are usually smaller but the libtcod window can be resized and any text will scale to match it.  The included libtcod fonts are based off of TTF's and don't look as bad as loading TTF's directly.
https://github.com/mad4j/curses.js/tree/master/sdlfonts (https://sourceforge.net/projects/pdcurses/files/sdlfonts/)
https://github.com/Tecate/bitmap-fonts
https://github.com/libtcod/libtcod/tree/develop/data/fonts

**Comment by jpuertos** [comment]
Oh thanks a lot for the tip and the links! after "setCustomFont" it works properly and beautifully!

**Comment by HexDecimal** [comment]
Closing this as I don't think there's anything more I can add.
