### ISSUE TITLE
Window font size not correct on my retina mac.

### ISSUE THREAD

**Issue by BreadPrince** [libtcod/libtcod#90]
### Screenshots

In order to describe this issue clearly, please see the following screenshots first:

**On retina screen**

![retina](https://user-images.githubusercontent.com/9443621/108295022-eb04dc80-71d1-11eb-9564-32a4e7fcae1e.png)

**On non-retina screen**

![non-retina](https://user-images.githubusercontent.com/9443621/108295184-361eef80-71d2-11eb-86dd-94f230a719f9.png)

### Description

This happens after I upgraded my macOS to **Big Sur**.

I'm using `TCOD_RENDERER_SDL2` renderer.

I can make it correct by **resizing** the window manually. I've checked the document, but I didn't found anything can resize the window programmatically.

**Comment by HexDecimal** [comment]
I'm not familiar with debugging this type of issue.  I can only guess that it might be High-DPI related.

Can you clarify what you mean by resizing the window manually?  Does libtcod not scale its output to fit the window when you resize it?

Libtcod's contexts give more control over creating the window, but the current C/C++ tutorials don't use it.  You'll have to use `TCOD_sys_get_sdl_window` to get the SDL window pointer and then use the SDL API to manipulate it, but that will break if the window creation step is fixed later.

Can you run your program with this environment variable? `SDL_VIDEO_HIGHDPI_DISABLED=1`

It can help if you're able to compile libtcod.  If you can't then I might be able to upload an experimental build for you to test.

**Comment by BreadPrince** [comment]
> Can you clarify what you mean by resizing the window manually?

It means drag the edge of the window by hand.

> Does libtcod not scale its output to fit the window when you resize it?

libtcod can scale it output correctly after resizng.

> Can you run your program with this environment variable? `SDL_VIDEO_HIGHDPI_DISABLED=1`

I can try compile libtcod, but I prefer use `TCOD_sys_get_sdl_window` first. Thanks for your help, I'll post here if I have any progress can help to fix this issue.

**Comment by HexDecimal** [comment]
>> Can you clarify what you mean by resizing the window manually?
>
> It means drag the edge of the window by hand.

I mean the scale isn't clear from the screenshots you've provided.  I assume that top screenshot is showing that tiles are trying to render off-screen, but it isn't clear that the tiles in the bottom screenshot are all on-screen.

> libtcod can scale it output correctly after resizng.

Does this mean all tiles are fit to the window after it'ss resized, and it stays that way no matter how you resize the window afterwards?

**Comment by BreadPrince** [comment]
> I mean the scale isn't clear from the screenshots you've provided. I assume that top screenshot is showing that tiles are trying to render off-screen, but it isn't clear that the tiles in the bottom screenshot are all on-screen.

Oh, I can confirm the tiles in the bottom screenshot are all on-screen, but in the top screenshot, only 1/4 tiles are renderred(top-left part of the bottom screenshot)

> Does this mean all tiles are fit to the window after it's resized, and it stays that way no matter how you resize the window afterwards?

Yes.

**Comment by HexDecimal** [comment]
Do the renderers `TCOD_RENDERER_OPENGL` and `TCOD_RENDERER_OPENGL2` have the same issue?

**Comment by BreadPrince** [comment]
`TCOD_RENDERER_OPENGL` does not have the same issue.

I cannot use `TCOD_RENDERER_OPENGL2`:

```
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Shader program failed to link:
ERROR: One or more attached shaders not successfully compiled
```

**Comment by HexDecimal** [comment]
I've attached a modified version which adds `SDL_WINDOW_ALLOW_HIGHDPI` to the window by default.  I'd like it if you could test this version.  You'll only need to replace `libtcod.dylib`.

[libtcod-1.16.1-x86_64-macos.tar.gz](https://github.com/libtcod/libtcod/files/6002510/libtcod-1.16.1-x86_64-macos.tar.gz)

**Comment by BreadPrince** [comment]
> I've attached a modified version which adds `SDL_WINDOW_ALLOW_HIGHDPI` to the window by default. I'd like it if you could test this version. You'll only need to replace `libtcod.dylib`.
> 
> [libtcod-1.16.1-x86_64-macos.tar.gz (highdpi)](https://github.com/libtcod/libtcod/files/6002510/libtcod-1.16.1-x86_64-macos.tar.gz)

Thanks, it works!

**Comment by HexDecimal** [comment]
That version worked right away?  With zero issues?

**Comment by BreadPrince** [comment]
Yes, I haven't found any issues now. You're awesome!

**Comment by HexDecimal** [comment]
One last question: Does the `TCOD_RENDERER_OPENGL` renderer still work correctly?

**Comment by BreadPrince** [comment]
Yes, it works
